const sources = {
    ip: [
        { id: 'AIPDB', name: 'AbuseIPDB', url: 'https://www.abuseipdb.com/', lookupurl: 'https://www.abuseipdb.com/check/' },
        { id: 'AVOTX', name: 'AlienVault OTX', url: 'https://otx.alienvault.com/', lookupurl: 'https://otx.alienvault.com/indicator/ip/' },
        { id: 'APNIC', name: 'APNIC', url: 'https://wq.apnic.net/', lookupurl: 'https://wq.apnic.net/static/search.html?query=' },
        { id: 'ARIN', name: 'ARIN', url: 'https://search.arin.net/rdap/', lookupurl: 'https://search.arin.net/rdap/?query=' },
        { id: 'BGPV', name: 'BGPView', url: 'https://bgpview.io/', lookupurl: 'https://bgpview.io/ip/' },
        { id: 'BRWLR', name: 'Browserling', url: 'https://www.browserling.com/', lookupurl: 'https://www.browserling.com/browse/win10/chrome127/' },
        { id: 'CENS', name: 'Censys', url: 'https://search.censys.io/', lookupurl: 'https://search.censys.io/hosts/' },
        { id: 'DNSLY', name: 'DNSlytics', url: 'https://dnslytics.com/', lookupurl: 'https://dnslytics.com/ip/' },
        { id: 'GGLS', name: 'Google Search', url: 'https://www.google.com', lookupurl: 'https://www.google.com/search?q=site%3A' },
        { id: 'GTREP', name: 'Google Transparency', url: 'https://transparencyreport.google.com/safe-browsing/search', lookupurl: 'https://transparencyreport.google.com/safe-browsing/search?url=' },
        { id: 'GRNOI', name: 'GreyNoise', url: 'https://viz.greynoise.io/', lookupurl: 'https://viz.greynoise.io/ip/' },
        { id: 'INXL', name: 'IntelX', url: 'https://intelx.io/', lookupurl: 'https://intelx.io/?s=' },
        { id: 'IP2LOC', name: 'IP2Location', url: 'https://www.ip2location.com/', lookupurl: 'https://www.ip2location.com/demo/' },
        { id: 'IPINF', name: 'IPinfo', url: 'https://ipinfo.io/', lookupurl: 'https://ipinfo.io/' },
        { id: 'IPQS', name: 'IPQualityScore', url: 'https://www.ipqualityscore.com/free-ip-lookup-proxy-vpn-test', lookupurl: 'https://www.ipqualityscore.com/vpn-ip-address-check/lookup/' },
        { id: 'IPV', name: 'IPVoid', url: 'https://www.ipvoid.com/', lookupurl: 'https://www.ipvoid.com/scan/' },
        { id: 'RIPE', name: 'RIPE NCC', url: 'https://www.ripe.net/' }, 
        { id: 'SHDN', name: 'Shodan', url: 'https://www.shodan.io', lookupurl: 'https://www.shodan.io/host/' },
        { id: 'SPUR', name: 'Spur', url: 'https://spur.us/' },
        { id: 'TLS', name: 'Talos', url: 'https://talosintelligence.com', lookupurl: 'https://talosintelligence.com/reputation_center/lookup?search=' },
        { id: 'THMNR', name: 'ThreatMiner', url: 'https://www.threatminer.org/', lookupurl: 'https://www.threatminer.org/host.php?q=' },
        { id: 'URLV', name: 'URLVoid', url: 'https://www.urlvoid.com/', lookupurl: 'https://www.urlvoid.com/ip/' },
        { id: 'VALKY', name: 'Valkyrie', url: 'https://verdict.valkyrie.comodo.com/', lookupurl: 'https://verdict.valkyrie.comodo.com/url/ip/result?ip=' },
        { id: 'VT', name: 'VirusTotal', url: 'https://www.virustotal.com/gui/home/search', lookupurl: 'https://www.virustotal.com/gui/ip-address/' },
        { id: 'WIGLE', name: 'WiGLE', url: 'https://wigle.net/' },
        { id: 'WHOIS', name: 'Whois', url: 'https://www.whois.com/whois/', lookupurl: 'https://www.whois.com/whois/' },
        { id: 'XFE', name: 'X-Force Exchange', url: 'https://exchange.xforce.ibmcloud.com/', lookupurl: 'https://exchange.xforce.ibmcloud.com/ip/' }
    ],
    domain: [
        { id: 'AIPDB', name: 'AbuseIPDB', url: 'https://www.abuseipdb.com/', lookupurl: 'https://www.abuseipdb.com/check/' },
        { id: 'AVOTX', name: 'AlienVault OTX', url: 'https://otx.alienvault.com/', lookupurl: 'https://otx.alienvault.com/indicator/domain/' },
        { id: 'BRWLR', name: 'Browserling', url: 'https://www.browserling.com/', lookupurl: 'https://www.browserling.com/browse/win10/chrome127/' },
        { id: 'CRT', name: 'crt.sh', url: 'https://crt.sh/' },
        { id: 'DNSD', name: 'DNSDumpster', url: 'https://dnsdumpster.com/' },
        { id: 'DNSLY', name: 'DNSlytics', url: 'https://dnslytics.com/', lookupurl: 'https://dnslytics.com/domain/' },
        { id: 'DOMT', name: 'DomainTools', url: 'https://whois.domaintools.com/', lookupurl: 'https://whois.domaintools.com/' },
        { id: 'GGLS', name: 'Google Search', url: 'https://www.google.com', lookupurl: 'https://www.google.com/search?q=site%3A' },
        { id: 'GTREP', name: 'Google Transparency', url: 'https://transparencyreport.google.com/safe-browsing/search', lookupurl: 'https://transparencyreport.google.com/safe-browsing/search?url=' },
        { id: 'HUNTR', name: 'Hunter.io', url: 'https://hunter.io/' },
        { id: 'ICANN', name: 'ICANN Lookup', url: 'https://lookup.icann.org/' },
        { id: 'INXL', name: 'IntelX', url: 'https://intelx.io/', lookupurl: 'https://intelx.io/?s=' },
        { id: 'IPQS', name: 'IPQualityScore', url: 'https://www.ipqualityscore.com/domain-reputation', lookupurl: 'https://www.ipqualityscore.com/domain-reputation/' },
        { id: 'SECTR', name: 'SecurityTrails', url: 'https://securitytrails.com/', lookupurl: 'https://securitytrails.com/domain/' },
        { id: 'SHDN', name: 'Shodan', url: 'https://www.shodan.io', lookupurl: 'https://www.shodan.io/domain/' },
        { id: 'TLS', name: 'Talos', url: 'https://talosintelligence.com', lookupurl: 'https://talosintelligence.com/reputation_center/lookup?search=' },
        { id: 'THMNR', name: 'ThreatMiner', url: 'https://www.threatminer.org/', lookupurl: 'https://www.threatminer.org/domain.php?q=' },
        { id: 'USIO', name: 'URLScan.io', url: 'https://urlscan.io', lookupurl: 'https://urlscan.io/domain/' },
        { id: 'VALKY', name: 'Valkyrie', url: 'https://verdict.valkyrie.comodo.com/', lookupurl: 'https://verdict.valkyrie.comodo.com/url/domain/result?domain=' },
        { id: 'VT', name: 'VirusTotal', url: 'https://www.virustotal.com/gui/home/search', lookupurl: 'https://www.virustotal.com/gui/domain/' },
        { id: 'WBMAC', name: 'Wayback Machine', url: 'https://web.archive.org/', lookupurl: 'https://web.archive.org/web/*/' },
        { id: 'WOT', name: 'Web of Trust', url: 'https://www.mywot.com/', lookupurl: 'https://www.mywot.com/en/scorecard/' },
        { id: 'WHOIS', name: 'Whois', url: 'https://www.whois.com/whois/', lookupurl: 'https://www.whois.com/whois/' },
        { id: 'WXAPI', name: 'WhoisXML API', url: 'https://whois.whoisxmlapi.com/', lookupurl: 'https://whois.whoisxmlapi.com/lookup/' },
        { id: 'XFE', name: 'X-Force Exchange', url: 'https://exchange.xforce.ibmcloud.com/', lookupurl: 'https://exchange.xforce.ibmcloud.com/url/' }
    ],
    hash: [
        { id: 'ARUN', name: 'Any.Run', url: 'https://app.any.run/', lookupurl: 'https://app.any.run/submissions/sample/' },
        { id: 'CIRCL', name: 'CIRCL', url: 'https://hash.circl.lu/' },
        { id: 'CKSAN', name: 'Cuckoo Sandbox', url: 'https://cuckoosandbox.org/', lookupurl: 'https://cuckoosandbox.org/sample/' },
        { id: 'GGLS', name: 'Google Search', url: 'https://www.google.com', lookupurl: 'https://www.google.com/search?q=' },
        { id: 'HYBAN', name: 'Hybrid Analysis', url: 'https://www.hybrid-analysis.com', lookupurl: 'https://www.hybrid-analysis.com/sample/' },
        { id: 'JSBX', name: 'Joe Sandbox', url: 'https://www.joesandbox.com/', lookupurl: 'https://www.joesandbox.com/search?q=' },
        { id: 'MLPRB', name: 'Malprob', url: 'https://malprob.io/', lookupurl: 'https://malprob.io/report/' },
        { id: 'MLSHR', name: 'MalShare', url: 'https://malshare.com/', lookupurl: 'https://malshare.com/sample.php?hash=' },
        { id: 'MLBZ', name: 'MalwareBazaar', url: 'https://bazaar.abuse.ch', lookupurl: 'https://bazaar.abuse.ch/sample/' },
        { id: 'METAD', name: 'MetaDefender', url: 'https://metadefender.opswat.com/', lookupurl: 'https://metadefender.opswat.com/results/file/' },
        { id: 'NIST', name: 'NIST NSRL', url: 'https://www.nist.gov/itl/ssd/software-quality-group/national-software-reference-library-nsrl' },
        { id: 'REVLAB', name: 'ReversingLabs', url: 'https://www.reversinglabs.com/', lookupurl: 'https://analysis.reversinglabs.com/sample/' },
        { id: 'TLS', name: 'Talos', url: 'https://talosintelligence.com', lookupurl: 'https://talosintelligence.com/talos_file_reputation?s=' },
        { id: 'THMNR', name: 'ThreatMiner', url: 'https://www.threatminer.org/', lookupurl: 'https://www.threatminer.org/sample.php?q=' },
        { id: 'TRGE', name: 'Triage', url: 'https://tria.ge/', lookupurl: 'https://tria.ge/sample/' },
        { id: 'VALHA', name: 'Valhalla', url: 'https://valhalla.nextron-systems.com/', lookupurl: 'https://valhalla.nextron-systems.com/sample/' },
        { id: 'VALKY', name: 'Valkyrie', url: 'https://verdict.valkyrie.comodo.com/', lookupurl: 'https://verdict.valkyrie.comodo.com/file/result?s=' },
        { id: 'VT', name: 'VirusTotal', url: 'https://www.virustotal.com/gui/home/search', lookupurl: 'https://www.virustotal.com/gui/file/' }
    ],
    bookmarks: [
        { id: 'BCAT', name: 'Bellingcat', url: 'https://www.bellingcat.com/' },
        { id: 'BING', name: 'Bing', url: 'https://www.bing.com/' },
        { id: 'BLCKC', name: 'Blockchain', url: 'https://www.blockchain.com/explorer' },
        { id: 'CHAT', name: 'ChatGPT', url: 'https://chatgpt.com/' },
        { id: 'COPIL', name: 'Copilot', url: 'https://copilot.microsoft.com/' },
        { id: 'CYCHF', name: 'CyberChef', url: 'https://gchq.github.io/CyberChef/' },
        { id: 'CYLCT', name: 'Cylect', url: 'https://cylect.io/' },
        { id: 'DDGO', name: 'DuckDuckGo', url: 'https://duckduckgo.com/' },
        { id: 'GEMINI', name: 'Gemini', url: 'https://gemini.google.com/' },
        { id: 'GGL', name: 'Google', url: 'https://www.google.com' },
        { id: 'GGADV', name: 'Google Adv Search', url: 'https://www.google.com/advanced_search' },
        { id: 'GGIMG', name: 'Google Images', url: 'https://images.google.com/' },
        { id: 'GOOS', name: 'Goosint', url: 'https://goosint.com/' },
        { id: 'HIBP', name: 'Have I Been Pwned', url: 'https://haveibeenpwned.com/' },
        { id: 'LINKD', name: 'LinkedIn', url: 'https://www.linkedin.com/' },
        { id: 'ONYPH', name: 'Onyphe', url: 'https://www.onyphe.io/' },
        { id: 'OSFMW', name: 'OSINT Framework', url: 'https://osintframework.com/' },
        { id: 'PSTBN', name: 'Pastebin', url: 'https://pastebin.com/' },
        { id: 'PERPX', name: 'Perplexity', url: 'https://www.perplexity.ai/' },
        { id: 'URLSH', name: 'URL Shortener', url: 'https://www.shorturl.at/' },
        { id: 'WBMAC', name: 'Wayback Machine', url: 'https://web.archive.org/' },
        { id: 'ZOOM', name: 'ZoomEye', url: 'https://www.zoomeye.org/' },
        { id: 'QRSCN', name: 'QR Code scanner', url: 'https://4qrcode.com/scan-qr-code.php' }
    ]
};